# Generated by Django 4.0.5 on 2022-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('NON', ''), ('FAS', 'Fashion'), ('TOY', 'Toys'), ('ELC', 'Electronics'), ('HOM', 'Home'), ('CAR', 'Cars')], max_length=3),
        ),
    ]
