# Generated by Django 4.0.5 on 2022-07-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_bid_remove_listing_lister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='user_listing', to='auctions.listing'),
        ),
    ]
