# Generated by Django 4.0.5 on 2022-07-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listing',
        ),
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_listing', to='auctions.listing'),
        ),
    ]
