# Generated by Django 4.0.5 on 2022-07-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listing',
        ),
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.listing'),
        ),
    ]
